import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | IsletIQ",
  description: "The terms governing your use of IsletIQ.",
};

export default function TermsPage() {
  return (
    <>
      <header className="mb-12">
        <div className="text-xs font-semibold text-[#0033a0] uppercase tracking-widest mb-3">
          Legal
        </div>
        <h1 className="text-4xl sm:text-5xl font-bold tracking-tight mb-3">
          Terms of Service
        </h1>
        <p className="text-sm text-[#94989e]">
          Effective: April 12, 2026 · Last updated: April 12, 2026
        </p>
      </header>

      <div className="space-y-8 text-[#666b78] leading-relaxed">
        <Section title="1. Acceptance of Terms">
          <p>
            By downloading, installing, or using IsletIQ (the
            &quot;Service&quot;), you agree to these Terms of Service (the
            &quot;Terms&quot;). If you do not agree to these Terms, do not
            use the Service.
          </p>
        </Section>

        <Section title="2. Not a Medical Device">
          <p className="rounded-lg border border-[#f2a633]/40 bg-[#fff7e6] p-4 text-[#7a5a14]">
            <strong className="text-[#a86b00]">IMPORTANT:</strong> IsletIQ
            is <strong>not</strong> a medical device. It has not been
            evaluated, cleared, or approved by the U.S. Food and Drug
            Administration (FDA) or any other regulatory body. IsletIQ is
            intended for informational, educational, and personal tracking
            purposes only. It is <strong>not</strong> a substitute for
            professional medical advice, diagnosis, or treatment.
          </p>
          <p>
            Any insulin dose suggestions, glucose targets, carbohydrate
            estimates, trend analyses, or other health-related output
            generated by IsletIQ, including by Agentic Sync, are{" "}
            <strong>informational only</strong>. You should not make
            medical, diabetes management, or dosing decisions based on this
            output without first consulting your physician or other
            qualified healthcare provider. Always verify glucose readings
            with a fingerstick test before making treatment decisions.
          </p>
          <p>
            Never disregard professional medical advice or delay seeking it
            because of something you read or saw in IsletIQ. If you think
            you may have a medical emergency, call your doctor or 911
            immediately.
          </p>
        </Section>

        <Section title="3. Eligibility">
          <p>
            You must be at least 13 years old to use IsletIQ. If you are
            under 18, you must have your parent or legal guardian&apos;s
            permission. By using IsletIQ, you represent that you meet these
            requirements.
          </p>
        </Section>

        <Section title="4. Account Responsibilities">
          <p>
            You are responsible for maintaining the confidentiality of your
            account credentials and for all activity that occurs under your
            account. Notify us immediately at{" "}
            <a
              href="mailto:hello@isletiq.com"
              className="text-[#0033a0] hover:underline"
            >
              hello@isletiq.com
            </a>{" "}
            if you suspect unauthorized use.
          </p>
        </Section>

        <Section title="5. Acceptable Use">
          <p>You agree not to:</p>
          <ul>
            <li>
              Use the Service in any way that violates applicable law or
              regulation.
            </li>
            <li>
              Reverse engineer, decompile, or disassemble any part of the
              Service except as permitted by law.
            </li>
            <li>
              Interfere with or disrupt the Service or its underlying
              infrastructure.
            </li>
            <li>
              Use the Service to provide medical advice to other people.
            </li>
            <li>
              Submit false or misleading data to circumvent safety
              mechanisms.
            </li>
          </ul>
        </Section>

        <Section title="6. Third-Party Services">
          <p>
            IsletIQ integrates with third-party services such as Apple
            HealthKit, Dexcom, Abbott LibreLink, and AI providers. Your use
            of those services is subject to their own terms and privacy
            policies. We are not responsible for the availability,
            accuracy, or content of third-party services.
          </p>
        </Section>

        <Section title="7. Intellectual Property">
          <p>
            IsletIQ, its name, logo, design, software, and content are
            owned by IsletIQ and protected by copyright, trademark, and
            other laws. We grant you a personal, non-transferable,
            revocable license to use the Service for your own personal,
            non-commercial use, subject to these Terms.
          </p>
          <p>
            You retain ownership of any health data, photos, or content you
            submit. By submitting it, you grant us the limited right to
            process it solely to provide the Service to you.
          </p>
        </Section>

        <Section title="8. Disclaimers">
          <p>
            THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS
            AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR
            IMPLIED, INCLUDING WITHOUT LIMITATION ANY WARRANTIES OF
            MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
            NON-INFRINGEMENT, OR ACCURACY. WE DO NOT WARRANT THAT THE
            SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL
            COMPONENTS, OR THAT ANY DATA WILL BE ACCURATE OR RELIABLE.
          </p>
        </Section>

        <Section title="9. Limitation of Liability">
          <p>
            TO THE FULLEST EXTENT PERMITTED BY LAW, ISLETIQ AND ITS
            AFFILIATES, OFFICERS, EMPLOYEES, AND AGENTS WILL NOT BE LIABLE
            FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR
            PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA, USE, GOODWILL,
            OR OTHER INTANGIBLE LOSSES, RESULTING FROM YOUR USE OF OR
            INABILITY TO USE THE SERVICE, INCLUDING BUT NOT LIMITED TO ANY
            HEALTH-RELATED OUTCOMES, DOSING DECISIONS, OR ACTIONS TAKEN OR
            NOT TAKEN BASED ON INFORMATION FROM THE SERVICE.
          </p>
          <p>
            OUR TOTAL CUMULATIVE LIABILITY TO YOU FOR ANY CLAIM ARISING OUT
            OF OR RELATING TO THESE TERMS OR THE SERVICE WILL NOT EXCEED
            THE GREATER OF (A) ONE HUNDRED U.S. DOLLARS ($100) OR (B) THE
            AMOUNT YOU PAID US, IF ANY, IN THE TWELVE MONTHS PRECEDING THE
            CLAIM.
          </p>
        </Section>

        <Section title="10. Indemnification">
          <p>
            You agree to indemnify, defend, and hold harmless IsletIQ from
            any claim, demand, loss, or damage, including reasonable
            attorneys&apos; fees, arising out of your use of the Service,
            your violation of these Terms, or your violation of any rights
            of another.
          </p>
        </Section>

        <Section title="11. Termination">
          <p>
            We may suspend or terminate your access to the Service at any
            time, with or without notice, for any reason, including
            violation of these Terms. You may stop using the Service at any
            time by deleting your account.
          </p>
        </Section>

        <Section title="12. Changes to These Terms">
          <p>
            We may revise these Terms from time to time. The most current
            version will always be posted at{" "}
            <a
              href="https://isletiq.com/terms"
              className="text-[#0033a0] hover:underline"
            >
              isletiq.com/terms
            </a>
            . Material changes will be communicated via the app or by
            email. Continued use of the Service after a change constitutes
            acceptance.
          </p>
        </Section>

        <Section title="13. Governing Law">
          <p>
            These Terms are governed by the laws of the United States and
            the State of California, without regard to conflict of laws
            principles. Any dispute arising under these Terms will be
            resolved exclusively in the state or federal courts located in
            California.
          </p>
        </Section>

        <Section title="14. Contact">
          <p>
            Questions about these Terms? Email{" "}
            <a
              href="mailto:hello@isletiq.com"
              className="text-[#0033a0] hover:underline"
            >
              hello@isletiq.com
            </a>
            .
          </p>
        </Section>
      </div>
    </>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section>
      <h2 className="text-xl font-semibold text-[#14171f] mb-3">{title}</h2>
      <div className="space-y-3 [&_ul]:list-disc [&_ul]:pl-6 [&_ul]:space-y-2 [&_li]:marker:text-[#94989e] [&_strong]:text-[#14171f]">
        {children}
      </div>
    </section>
  );
}
